/******************************************************************************/
// 
// Copyright (c) 2019 Esteban Egea-Lopez http://ait.upct.es/eegea
// 
/*******************************************************************************/



//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.6.1055.0.
// 

namespace Veneris {
/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("tazs", Namespace="", IsNullable=false)]
public partial class tazsType {
    
    private tazType[] tazField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("taz")]
    public tazType[] taz {
        get {
            return this.tazField;
        }
        set {
            this.tazField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class tazType {
    
    private tazSubType[] tazSourceField;
    
    private tazSubType[] tazSinkField;
    
    private string idField;
    
    private string edgesField;
    
    private string shapeField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("tazSource")]
    public tazSubType[] tazSource {
        get {
            return this.tazSourceField;
        }
        set {
            this.tazSourceField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("tazSink")]
    public tazSubType[] tazSink {
        get {
            return this.tazSinkField;
        }
        set {
            this.tazSinkField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string edges {
        get {
            return this.edgesField;
        }
        set {
            this.edgesField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string shape {
        get {
            return this.shapeField;
        }
        set {
            this.shapeField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class tazSubType {
    
    private string idField;
    
    private float weightField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class roundaboutType {
    
    private string nodesField;
    
    private string edgesField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nodes {
        get {
            return this.nodesField;
        }
        set {
            this.nodesField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string edges {
        get {
            return this.edgesField;
        }
        set {
            this.edgesField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class prohibitionType {
    
    private string prohibitorField;
    
    private string prohibitedField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string prohibitor {
        get {
            return this.prohibitorField;
        }
        set {
            this.prohibitorField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string prohibited {
        get {
            return this.prohibitedField;
        }
        set {
            this.prohibitedField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class connectionType {
    
    private string fromField;
    
    private string toField;
    
    private string fromLaneField;
    
    private string toLaneField;
    
    private boolType passField;
    
    private bool passFieldSpecified;
    
    private boolType keepClearField;
    
    private bool keepClearFieldSpecified;
    
    private float contPosField;
    
    private bool contPosFieldSpecified;
    
    private float visibilityField;
    
    private bool visibilityFieldSpecified;
    
    private string viaField;
    
    private string tlField;
    
    private string linkIndexField;
    
    private connectionTypeDir dirField;
    
    private connectionTypeState stateField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string from {
        get {
            return this.fromField;
        }
        set {
            this.fromField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string to {
        get {
            return this.toField;
        }
        set {
            this.toField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string fromLane {
        get {
            return this.fromLaneField;
        }
        set {
            this.fromLaneField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string toLane {
        get {
            return this.toLaneField;
        }
        set {
            this.toLaneField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public boolType pass {
        get {
            return this.passField;
        }
        set {
            this.passField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool passSpecified {
        get {
            return this.passFieldSpecified;
        }
        set {
            this.passFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public boolType keepClear {
        get {
            return this.keepClearField;
        }
        set {
            this.keepClearField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool keepClearSpecified {
        get {
            return this.keepClearFieldSpecified;
        }
        set {
            this.keepClearFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float contPos {
        get {
            return this.contPosField;
        }
        set {
            this.contPosField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool contPosSpecified {
        get {
            return this.contPosFieldSpecified;
        }
        set {
            this.contPosFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float visibility {
        get {
            return this.visibilityField;
        }
        set {
            this.visibilityField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool visibilitySpecified {
        get {
            return this.visibilityFieldSpecified;
        }
        set {
            this.visibilityFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string via {
        get {
            return this.viaField;
        }
        set {
            this.viaField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tl {
        get {
            return this.tlField;
        }
        set {
            this.tlField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string linkIndex {
        get {
            return this.linkIndexField;
        }
        set {
            this.linkIndexField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public connectionTypeDir dir {
        get {
            return this.dirField;
        }
        set {
            this.dirField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public connectionTypeState state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
public enum boolType {
    
    /// <comentarios/>
    @true,
    
    /// <comentarios/>
    @false,
    
    /// <comentarios/>
    True,
    
    /// <comentarios/>
    False,
    
    /// <comentarios/>
    yes,
    
    /// <comentarios/>
    no,
    
    /// <comentarios/>
    on,
    
    /// <comentarios/>
    off,
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <comentarios/>
    x,
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlEnumAttribute("-")]
    Item,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum connectionTypeDir {
    
    /// <comentarios/>
    s,
    
    /// <comentarios/>
    t,
    
    /// <comentarios/>
    T,
    
    /// <comentarios/>
    l,
    
    /// <comentarios/>
    r,
    
    /// <comentarios/>
    L,
    
    /// <comentarios/>
    R,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum connectionTypeState {
    
    /// <comentarios/>
    M,
    
    /// <comentarios/>
    m,
    
    /// <comentarios/>
    o,
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlEnumAttribute("=")]
    Item,
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlEnumAttribute("-")]
    Item1,
    
    /// <comentarios/>
    s,
    
    /// <comentarios/>
    w,
    
    /// <comentarios/>
    Z,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class requestType {
    
    private string indexField;
    
    private string responseField;
    
    private string foesField;
    
    private boolType contField;
    
    private bool contFieldSpecified;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string index {
        get {
            return this.indexField;
        }
        set {
            this.indexField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string response {
        get {
            return this.responseField;
        }
        set {
            this.responseField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string foes {
        get {
            return this.foesField;
        }
        set {
            this.foesField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public boolType cont {
        get {
            return this.contField;
        }
        set {
            this.contField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool contSpecified {
        get {
            return this.contFieldSpecified;
        }
        set {
            this.contFieldSpecified = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class junctionType {
    
    private requestType[] requestField;
    
    private string idField;
    
    private float xField;
    
    private float yField;
    
    private float zField;
    
    private bool zFieldSpecified;
    
    private junctionTypeType typeField;
    
    private string incLanesField;
    
    private string intLanesField;
    
    private string shapeField;
    
    private float radiusField;
    
    private bool radiusFieldSpecified;
    
    private boolType customShapeField;
    
    private bool customShapeFieldSpecified;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("request")]
    public requestType[] request {
        get {
            return this.requestField;
        }
        set {
            this.requestField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float x {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float z {
        get {
            return this.zField;
        }
        set {
            this.zField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool zSpecified {
        get {
            return this.zFieldSpecified;
        }
        set {
            this.zFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public junctionTypeType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string incLanes {
        get {
            return this.incLanesField;
        }
        set {
            this.incLanesField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string intLanes {
        get {
            return this.intLanesField;
        }
        set {
            this.intLanesField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string shape {
        get {
            return this.shapeField;
        }
        set {
            this.shapeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float radius {
        get {
            return this.radiusField;
        }
        set {
            this.radiusField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool radiusSpecified {
        get {
            return this.radiusFieldSpecified;
        }
        set {
            this.radiusFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public boolType customShape {
        get {
            return this.customShapeField;
        }
        set {
            this.customShapeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool customShapeSpecified {
        get {
            return this.customShapeFieldSpecified;
        }
        set {
            this.customShapeFieldSpecified = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum junctionTypeType {
    
    /// <comentarios/>
    traffic_light,
    
    /// <comentarios/>
    right_before_left,
    
    /// <comentarios/>
    priority,
    
    /// <comentarios/>
    dead_end,
    
    /// <comentarios/>
    unregulated,
    
    /// <comentarios/>
    traffic_light_unregulated,
    
    /// <comentarios/>
    allway_stop,
    
    /// <comentarios/>
    priority_stop,
    
    /// <comentarios/>
    rail_signal,
    
    /// <comentarios/>
    zipper,
    
    /// <comentarios/>
    rail_crossing,
    
    /// <comentarios/>
    traffic_light_right_on_red,
    
    /// <comentarios/>
    @internal,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class phaseType {
    
    private float durationField;
    
    private float minDurField;
    
    private bool minDurFieldSpecified;
    
    private float maxDurField;
    
    private bool maxDurFieldSpecified;
    
    private string stateField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float duration {
        get {
            return this.durationField;
        }
        set {
            this.durationField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float minDur {
        get {
            return this.minDurField;
        }
        set {
            this.minDurField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool minDurSpecified {
        get {
            return this.minDurFieldSpecified;
        }
        set {
            this.minDurFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float maxDur {
        get {
            return this.maxDurField;
        }
        set {
            this.maxDurField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maxDurSpecified {
        get {
            return this.maxDurFieldSpecified;
        }
        set {
            this.maxDurFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class tlLogicType {
    
    private object[] itemsField;
    
    private string idField;
    
    private tlTypeType typeField;
    
    private string programIDField;
    
    private float offsetField;
    
    private bool offsetFieldSpecified;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("param", typeof(paramType))]
    [System.Xml.Serialization.XmlElementAttribute("phase", typeof(phaseType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public tlTypeType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string programID {
        get {
            return this.programIDField;
        }
        set {
            this.programIDField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float offset {
        get {
            return this.offsetField;
        }
        set {
            this.offsetField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool offsetSpecified {
        get {
            return this.offsetFieldSpecified;
        }
        set {
            this.offsetFieldSpecified = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class paramType {
    
    private string keyField;
    
    private string valueField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
public enum tlTypeType {
    
    /// <comentarios/>
    actuated,
    
    /// <comentarios/>
    @static,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class neighType {
    
    private string laneField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lane {
        get {
            return this.laneField;
        }
        set {
            this.laneField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class laneType {
    
    private neighType[] neighField;
    
    private paramType[] paramField;
    
    private string idField;
    
    private string indexField;
    
    private string allowField;
    
    private string disallowField;
    
    private string preferField;
    
    private float speedField;
    
    private float lengthField;
    
    private float endOffsetField;
    
    private bool endOffsetFieldSpecified;
    
    private float widthField;
    
    private bool widthFieldSpecified;
    
    private string shapeField;
    
    private boolType customShapeField;
    
    private bool customShapeFieldSpecified;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("neigh")]
    public neighType[] neigh {
        get {
            return this.neighField;
        }
        set {
            this.neighField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("param")]
    public paramType[] param {
        get {
            return this.paramField;
        }
        set {
            this.paramField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string index {
        get {
            return this.indexField;
        }
        set {
            this.indexField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string allow {
        get {
            return this.allowField;
        }
        set {
            this.allowField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string disallow {
        get {
            return this.disallowField;
        }
        set {
            this.disallowField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string prefer {
        get {
            return this.preferField;
        }
        set {
            this.preferField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float speed {
        get {
            return this.speedField;
        }
        set {
            this.speedField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float length {
        get {
            return this.lengthField;
        }
        set {
            this.lengthField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float endOffset {
        get {
            return this.endOffsetField;
        }
        set {
            this.endOffsetField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool endOffsetSpecified {
        get {
            return this.endOffsetFieldSpecified;
        }
        set {
            this.endOffsetFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool widthSpecified {
        get {
            return this.widthFieldSpecified;
        }
        set {
            this.widthFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string shape {
        get {
            return this.shapeField;
        }
        set {
            this.shapeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public boolType customShape {
        get {
            return this.customShapeField;
        }
        set {
            this.customShapeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool customShapeSpecified {
        get {
            return this.customShapeFieldSpecified;
        }
        set {
            this.customShapeFieldSpecified = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class edgeType {
    
    private laneType[] laneField;
    
    private paramType[] paramField;
    
    private string idField;
    
    private edgeTypeFunction functionField;
    
    private bool functionFieldSpecified;
    
    private string fromField;
    
    private string toField;
    
    private string nameField;
    
    private string priorityField;
    
    private float lengthField;
    
    private bool lengthFieldSpecified;
    
    private string typeField;
    
    private string shapeField;
    
    private edgeTypeSpreadType spreadTypeField;
    
    private bool spreadTypeFieldSpecified;
    
    private string crossingEdgesField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("lane")]
    public laneType[] lane {
        get {
            return this.laneField;
        }
        set {
            this.laneField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("param")]
    public paramType[] param {
        get {
            return this.paramField;
        }
        set {
            this.paramField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public edgeTypeFunction function {
        get {
            return this.functionField;
        }
        set {
            this.functionField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool functionSpecified {
        get {
            return this.functionFieldSpecified;
        }
        set {
            this.functionFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string from {
        get {
            return this.fromField;
        }
        set {
            this.fromField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string to {
        get {
            return this.toField;
        }
        set {
            this.toField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float length {
        get {
            return this.lengthField;
        }
        set {
            this.lengthField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool lengthSpecified {
        get {
            return this.lengthFieldSpecified;
        }
        set {
            this.lengthFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string shape {
        get {
            return this.shapeField;
        }
        set {
            this.shapeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public edgeTypeSpreadType spreadType {
        get {
            return this.spreadTypeField;
        }
        set {
            this.spreadTypeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool spreadTypeSpecified {
        get {
            return this.spreadTypeFieldSpecified;
        }
        set {
            this.spreadTypeFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string crossingEdges {
        get {
            return this.crossingEdgesField;
        }
        set {
            this.crossingEdgesField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum edgeTypeFunction {
    
    /// <comentarios/>
    normal,
    
    /// <comentarios/>
    @internal,
    
    /// <comentarios/>
    connector,
    
    /// <comentarios/>
    crossing,
    
    /// <comentarios/>
    walkingarea,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum edgeTypeSpreadType {
    
    /// <comentarios/>
    center,
    
    /// <comentarios/>
    right,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class restrictionType {
    
    private string vClassField;
    
    private float speedField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string vClass {
        get {
            return this.vClassField;
        }
        set {
            this.vClassField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float speed {
        get {
            return this.speedField;
        }
        set {
            this.speedField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class typeType {
    
    private restrictionType[] itemsField;
    
    private string idField;
    
    private string allowField;
    
    private string disallowField;
    
    private int priorityField;
    
    private bool priorityFieldSpecified;
    
    private int numLanesField;
    
    private bool numLanesFieldSpecified;
    
    private float speedField;
    
    private bool speedFieldSpecified;
    
    private boolType discardField;
    
    private bool discardFieldSpecified;
    
    private boolType onewayField;
    
    private bool onewayFieldSpecified;
    
    private float widthField;
    
    private bool widthFieldSpecified;
    
    private float sidewalkWidthField;
    
    private bool sidewalkWidthFieldSpecified;
    
    private float bikeLaneWidthField;
    
    private bool bikeLaneWidthFieldSpecified;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("restriction")]
    public restrictionType[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string allow {
        get {
            return this.allowField;
        }
        set {
            this.allowField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string disallow {
        get {
            return this.disallowField;
        }
        set {
            this.disallowField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool prioritySpecified {
        get {
            return this.priorityFieldSpecified;
        }
        set {
            this.priorityFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int numLanes {
        get {
            return this.numLanesField;
        }
        set {
            this.numLanesField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool numLanesSpecified {
        get {
            return this.numLanesFieldSpecified;
        }
        set {
            this.numLanesFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float speed {
        get {
            return this.speedField;
        }
        set {
            this.speedField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool speedSpecified {
        get {
            return this.speedFieldSpecified;
        }
        set {
            this.speedFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public boolType discard {
        get {
            return this.discardField;
        }
        set {
            this.discardField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool discardSpecified {
        get {
            return this.discardFieldSpecified;
        }
        set {
            this.discardFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public boolType oneway {
        get {
            return this.onewayField;
        }
        set {
            this.onewayField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool onewaySpecified {
        get {
            return this.onewayFieldSpecified;
        }
        set {
            this.onewayFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool widthSpecified {
        get {
            return this.widthFieldSpecified;
        }
        set {
            this.widthFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float sidewalkWidth {
        get {
            return this.sidewalkWidthField;
        }
        set {
            this.sidewalkWidthField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool sidewalkWidthSpecified {
        get {
            return this.sidewalkWidthFieldSpecified;
        }
        set {
            this.sidewalkWidthFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float bikeLaneWidth {
        get {
            return this.bikeLaneWidthField;
        }
        set {
            this.bikeLaneWidthField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool bikeLaneWidthSpecified {
        get {
            return this.bikeLaneWidthFieldSpecified;
        }
        set {
            this.bikeLaneWidthFieldSpecified = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class locationType {
    
    private string netOffsetField;
    
    private string convBoundaryField;
    
    private string origBoundaryField;
    
    private string projParameterField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string netOffset {
        get {
            return this.netOffsetField;
        }
        set {
            this.netOffsetField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string convBoundary {
        get {
            return this.convBoundaryField;
        }
        set {
            this.convBoundaryField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string origBoundary {
        get {
            return this.origBoundaryField;
        }
        set {
            this.origBoundaryField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string projParameter {
        get {
            return this.projParameterField;
        }
        set {
            this.projParameterField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("net", Namespace="", IsNullable=false)]
public partial class netType {
    
    private locationType locationField;
    
    private typeType[] typeField;
    
    private edgeType[] edgeField;
    
    private tlLogicType[] tlLogicField;
    
    private junctionType[] junctionField;
    
    private connectionType[] connectionField;
    
    private prohibitionType[] prohibitionField;
    
    private roundaboutType[] roundaboutField;
    
    private tazType[] tazField;
    
    private string versionField;
    
    private int junctionCornerDetailField;
    
    private bool junctionCornerDetailFieldSpecified;
    
    private int junctionLinkDetailField;
    
    private bool junctionLinkDetailFieldSpecified;
    
    private boolType lefthandField;
    
    private bool lefthandFieldSpecified;
    
    /// <comentarios/>
    public locationType location {
        get {
            return this.locationField;
        }
        set {
            this.locationField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("type")]
    public typeType[] type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("edge")]
    public edgeType[] edge {
        get {
            return this.edgeField;
        }
        set {
            this.edgeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("tlLogic")]
    public tlLogicType[] tlLogic {
        get {
            return this.tlLogicField;
        }
        set {
            this.tlLogicField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("junction")]
    public junctionType[] junction {
        get {
            return this.junctionField;
        }
        set {
            this.junctionField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("connection")]
    public connectionType[] connection {
        get {
            return this.connectionField;
        }
        set {
            this.connectionField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("prohibition")]
    public prohibitionType[] prohibition {
        get {
            return this.prohibitionField;
        }
        set {
            this.prohibitionField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("roundabout")]
    public roundaboutType[] roundabout {
        get {
            return this.roundaboutField;
        }
        set {
            this.roundaboutField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("taz")]
    public tazType[] taz {
        get {
            return this.tazField;
        }
        set {
            this.tazField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int junctionCornerDetail {
        get {
            return this.junctionCornerDetailField;
        }
        set {
            this.junctionCornerDetailField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool junctionCornerDetailSpecified {
        get {
            return this.junctionCornerDetailFieldSpecified;
        }
        set {
            this.junctionCornerDetailFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int junctionLinkDetail {
        get {
            return this.junctionLinkDetailField;
        }
        set {
            this.junctionLinkDetailField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool junctionLinkDetailSpecified {
        get {
            return this.junctionLinkDetailFieldSpecified;
        }
        set {
            this.junctionLinkDetailFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public boolType lefthand {
        get {
            return this.lefthandField;
        }
        set {
            this.lefthandField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool lefthandSpecified {
        get {
            return this.lefthandFieldSpecified;
        }
        set {
            this.lefthandFieldSpecified = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("types", Namespace="", IsNullable=false)]
public partial class typesType {
    
    private typeType[] typeField;
    
    private string versionField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("type")]
    public typeType[] type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("connections", Namespace="", IsNullable=false)]
public partial class connectionsType {
    
    private object[] itemsField;
    
    private string versionField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("connection", typeof(connectionType))]
    [System.Xml.Serialization.XmlElementAttribute("crossing", typeof(crossingType))]
    [System.Xml.Serialization.XmlElementAttribute("customShape", typeof(customShapeType))]
    [System.Xml.Serialization.XmlElementAttribute("delete", typeof(deleteType))]
    [System.Xml.Serialization.XmlElementAttribute("prohibition", typeof(prohibitionType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class crossingType {
    
    private string nodeField;
    
    private string edgesField;
    
    private int priorityField;
    
    private bool priorityFieldSpecified;
    
    private float widthField;
    
    private bool widthFieldSpecified;
    
    private boolType discardField;
    
    private bool discardFieldSpecified;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string node {
        get {
            return this.nodeField;
        }
        set {
            this.nodeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string edges {
        get {
            return this.edgesField;
        }
        set {
            this.edgesField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool prioritySpecified {
        get {
            return this.priorityFieldSpecified;
        }
        set {
            this.priorityFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool widthSpecified {
        get {
            return this.widthFieldSpecified;
        }
        set {
            this.widthFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public boolType discard {
        get {
            return this.discardField;
        }
        set {
            this.discardField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool discardSpecified {
        get {
            return this.discardFieldSpecified;
        }
        set {
            this.discardFieldSpecified = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class customShapeType {
    
    private string idField;
    
    private string shapeField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string shape {
        get {
            return this.shapeField;
        }
        set {
            this.shapeField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class deleteType {
    
    private string fromField;
    
    private string toField;
    
    private string fromLaneField;
    
    private string toLaneField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string from {
        get {
            return this.fromField;
        }
        set {
            this.fromField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string to {
        get {
            return this.toField;
        }
        set {
            this.toField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string fromLane {
        get {
            return this.fromLaneField;
        }
        set {
            this.fromLaneField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string toLane {
        get {
            return this.toLaneField;
        }
        set {
            this.toLaneField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("edges", Namespace="", IsNullable=false)]
public partial class edgesType {
    
    private edgeType[] edgeField;
    
    private roundaboutType[] roundaboutField;
    
    private string versionField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("edge")]
    public edgeType[] edge {
        get {
            return this.edgeField;
        }
        set {
            this.edgeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("roundabout")]
    public roundaboutType[] roundabout {
        get {
            return this.roundaboutField;
        }
        set {
            this.roundaboutField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("nodes", Namespace="", IsNullable=false)]
public partial class nodesType {
    
    private locationType locationField;
    
    private object[] itemsField;
    
    private string versionField;
    
    /// <comentarios/>
    public locationType location {
        get {
            return this.locationField;
        }
        set {
            this.locationField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("delete", typeof(deleteType))]
    [System.Xml.Serialization.XmlElementAttribute("join", typeof(joinType))]
    [System.Xml.Serialization.XmlElementAttribute("joinExclude", typeof(joinExcludeType))]
    [System.Xml.Serialization.XmlElementAttribute("node", typeof(nodeType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class joinType {
    
    private string nodesField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nodes {
        get {
            return this.nodesField;
        }
        set {
            this.nodesField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class joinExcludeType {
    
    private string nodesField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nodes {
        get {
            return this.nodesField;
        }
        set {
            this.nodesField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class nodeType {
    
    private string idField;
    
    private float xField;
    
    private bool xFieldSpecified;
    
    private float yField;
    
    private bool yFieldSpecified;
    
    private float zField;
    
    private bool zFieldSpecified;
    
    private nodeTypeType typeField;
    
    private bool typeFieldSpecified;
    
    private string tlField;
    
    private tlTypeType tlTypeField;
    
    private bool tlTypeFieldSpecified;
    
    private string controlledInnerField;
    
    private string shapeField;
    
    private float radiusField;
    
    private bool radiusFieldSpecified;
    
    private boolType keepClearField;
    
    private bool keepClearFieldSpecified;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float x {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool xSpecified {
        get {
            return this.xFieldSpecified;
        }
        set {
            this.xFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ySpecified {
        get {
            return this.yFieldSpecified;
        }
        set {
            this.yFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float z {
        get {
            return this.zField;
        }
        set {
            this.zField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool zSpecified {
        get {
            return this.zFieldSpecified;
        }
        set {
            this.zFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public nodeTypeType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool typeSpecified {
        get {
            return this.typeFieldSpecified;
        }
        set {
            this.typeFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tl {
        get {
            return this.tlField;
        }
        set {
            this.tlField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public tlTypeType tlType {
        get {
            return this.tlTypeField;
        }
        set {
            this.tlTypeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool tlTypeSpecified {
        get {
            return this.tlTypeFieldSpecified;
        }
        set {
            this.tlTypeFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string controlledInner {
        get {
            return this.controlledInnerField;
        }
        set {
            this.controlledInnerField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string shape {
        get {
            return this.shapeField;
        }
        set {
            this.shapeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float radius {
        get {
            return this.radiusField;
        }
        set {
            this.radiusField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool radiusSpecified {
        get {
            return this.radiusFieldSpecified;
        }
        set {
            this.radiusFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public boolType keepClear {
        get {
            return this.keepClearField;
        }
        set {
            this.keepClearField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool keepClearSpecified {
        get {
            return this.keepClearFieldSpecified;
        }
        set {
            this.keepClearFieldSpecified = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
public enum nodeTypeType {
    
    /// <comentarios/>
    traffic_light,
    
    /// <comentarios/>
    right_before_left,
    
    /// <comentarios/>
    priority,
    
    /// <comentarios/>
    dead_end,
    
    /// <comentarios/>
    unregulated,
    
    /// <comentarios/>
    traffic_light_unregulated,
    
    /// <comentarios/>
    rail_signal,
    
    /// <comentarios/>
    allway_stop,
    
    /// <comentarios/>
    priority_stop,
    
    /// <comentarios/>
    zipper,
    
    /// <comentarios/>
    rail_crossing,
    
    /// <comentarios/>
    traffic_light_right_on_red,
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("tlLogics", Namespace="", IsNullable=false)]
public partial class tlLogicsType {
    
    private object[] itemsField;
    
    private ItemsChoiceType[] itemsElementNameField;
    
    private string versionField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("connection", typeof(connectionDeleteType))]
    [System.Xml.Serialization.XmlElementAttribute("delete", typeof(connectionDeleteType))]
    [System.Xml.Serialization.XmlElementAttribute("tlLogic", typeof(tlLogicType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class connectionDeleteType {
    
    private string fromField;
    
    private string toField;
    
    private string fromLaneField;
    
    private string toLaneField;
    
    private string tlField;
    
    private string linkIndexField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string from {
        get {
            return this.fromField;
        }
        set {
            this.fromField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string to {
        get {
            return this.toField;
        }
        set {
            this.toField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string fromLane {
        get {
            return this.fromLaneField;
        }
        set {
            this.fromLaneField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string toLane {
        get {
            return this.toLaneField;
        }
        set {
            this.toLaneField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tl {
        get {
            return this.tlField;
        }
        set {
            this.tlField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string linkIndex {
        get {
            return this.linkIndexField;
        }
        set {
            this.linkIndexField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
public enum ItemsChoiceType {
    
    /// <comentarios/>
    connection,
    
    /// <comentarios/>
    delete,
    
    /// <comentarios/>
    tlLogic,
}

}