// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SivertAPI.PosUpdNoMultiGSCM
{

using global::System;
using global::FlatBuffers;

public struct VehInfo : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public VehInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { return __p.bb.GetInt(__p.bb_pos + 0); } }
  public float TimeStamp { get { return __p.bb.GetFloat(__p.bb_pos + 4); } }

  public static Offset<VehInfo> CreateVehInfo(FlatBufferBuilder builder, int Id, float TimeStamp) {
    builder.Prep(4, 8);
    builder.PutFloat(TimeStamp);
    builder.PutInt(Id);
    return new Offset<VehInfo>(builder.Offset);
  }
};


}
