/******************************************************************************/
// 
// Copyright (c) 2019 Esteban Egea-Lopez http://ait.upct.es/eegea
// 
/*******************************************************************************/



// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Veneris.Communications
{

using global::System;
using global::FlatBuffers;

public struct RemoveDynamicMeshGroup : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static RemoveDynamicMeshGroup GetRootAsRemoveDynamicMeshGroup(ByteBuffer _bb) { return GetRootAsRemoveDynamicMeshGroup(_bb, new RemoveDynamicMeshGroup()); }
  public static RemoveDynamicMeshGroup GetRootAsRemoveDynamicMeshGroup(ByteBuffer _bb, RemoveDynamicMeshGroup obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RemoveDynamicMeshGroup __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<RemoveDynamicMeshGroup> CreateRemoveDynamicMeshGroup(FlatBufferBuilder builder,
      int id = 0) {
    builder.StartObject(1);
    RemoveDynamicMeshGroup.AddId(builder, id);
    return RemoveDynamicMeshGroup.EndRemoveDynamicMeshGroup(builder);
  }

  public static void StartRemoveDynamicMeshGroup(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static Offset<RemoveDynamicMeshGroup> EndRemoveDynamicMeshGroup(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RemoveDynamicMeshGroup>(o);
  }
  public static void FinishRemoveDynamicMeshGroupBuffer(FlatBufferBuilder builder, Offset<RemoveDynamicMeshGroup> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedRemoveDynamicMeshGroupBuffer(FlatBufferBuilder builder, Offset<RemoveDynamicMeshGroup> offset) { builder.FinishSizePrefixed(offset.Value); }
};


}
