/******************************************************************************/
// 
// Copyright (c) 2019 Esteban Egea-Lopez http://ait.upct.es/eegea
// 
/*******************************************************************************/



// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Veneris.Communications
{

public enum VenerisMessageTypes : uint
{
 Reserved = 0,
 Create = 1,
 Destroy = 2,
 VehicleState = 3,
 ExternalTime = 4,
 End = 5,
 UseOpal = 6,
 FinishOpalContext = 7,
 StaticMesh = 8,
 AddDynamicMeshGroup = 9,
 RemoveDynamicMeshGroup = 10,
 UpdateTransformInGroup = 11,
 FinishDynamicMeshGroup = 12,
 DynamicMesh = 13,
};


}
