// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SivertAPI.PosUpd
{

using global::System;
using global::FlatBuffers;

public struct Channel : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Channel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int TxID { get { return __p.bb.GetInt(__p.bb_pos + 0); } }
  public int RxID { get { return __p.bb.GetInt(__p.bb_pos + 4); } }
  public int ChannelIDinfo { get { return __p.bb.GetInt(__p.bb_pos + 8); } }

  public static Offset<Channel> CreateChannel(FlatBufferBuilder builder, int TxID, int RxID, int ChannelIDinfo) {
    builder.Prep(4, 12);
    builder.PutInt(ChannelIDinfo);
    builder.PutInt(RxID);
    builder.PutInt(TxID);
    return new Offset<Channel>(builder.Offset);
  }
};


}
