// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SivertAPI.PosUpd
{

using global::System;
using global::FlatBuffers;

public struct EEBL : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public EEBL __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Triggered { get { return 0!=__p.bb.Get(__p.bb_pos + 0); } }
  public int VehID { get { return __p.bb.GetInt(__p.bb_pos + 4); } }

  public static Offset<EEBL> CreateEEBL(FlatBufferBuilder builder, bool Triggered, int VehID) {
    builder.Prep(4, 8);
    builder.PutInt(VehID);
    builder.Pad(3);
    builder.PutBool(Triggered);
    return new Offset<EEBL>(builder.Offset);
  }
};


}
