// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SivertAPI.PosUpd
{

using global::System;
using global::FlatBuffers;

public struct PosAPI : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static PosAPI GetRootAsPosAPI(ByteBuffer _bb) { return GetRootAsPosAPI(_bb, new PosAPI()); }
  public static PosAPI GetRootAsPosAPI(ByteBuffer _bb, PosAPI obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public PosAPI __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public GSCMstruct? GSCM { get { int o = __p.__offset(4); return o != 0 ? (GSCMstruct?)(new GSCMstruct()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public GscmInfo? GSCMvector(int j) { int o = __p.__offset(6); return o != 0 ? (GscmInfo?)(new GscmInfo()).__assign(__p.__vector(o) + j * 16, __p.bb) : null; }
  public int GSCMvectorLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
  public EEBL? CITS(int j) { int o = __p.__offset(8); return o != 0 ? (EEBL?)(new EEBL()).__assign(__p.__vector(o) + j * 8, __p.bb) : null; }
  public int CITSLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
  public Vec3API? Pos(int j) { int o = __p.__offset(10); return o != 0 ? (Vec3API?)(new Vec3API()).__assign(__p.__vector(o) + j * 16, __p.bb) : null; }
  public int PosLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }
  public VehInfo? Suppl(int j) { int o = __p.__offset(12); return o != 0 ? (VehInfo?)(new VehInfo()).__assign(__p.__vector(o) + j * 8, __p.bb) : null; }
  public int SupplLength { get { int o = __p.__offset(12); return o != 0 ? __p.__vector_len(o) : 0; } }
  public bool TerminateNS3 { get { int o = __p.__offset(14); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public SpectrumValue? GSCMSpectruChannels(int j) { int o = __p.__offset(16); return o != 0 ? (SpectrumValue?)(new SpectrumValue()).__assign(__p.__vector(o) + j * 24, __p.bb) : null; }
  public int GSCMSpectruChannelsLength { get { int o = __p.__offset(16); return o != 0 ? __p.__vector_len(o) : 0; } }
  public Channel? SpectrumInfo(int j) { int o = __p.__offset(18); return o != 0 ? (Channel?)(new Channel()).__assign(__p.__vector(o) + j * 12, __p.bb) : null; }
  public int SpectrumInfoLength { get { int o = __p.__offset(18); return o != 0 ? __p.__vector_len(o) : 0; } }
  public int NumberOfFrequnciesPerChannel { get { int o = __p.__offset(20); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string V2Xstack { get { int o = __p.__offset(22); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetV2XstackBytes() { return __p.__vector_as_span(22); }
#else
  public ArraySegment<byte>? GetV2XstackBytes() { return __p.__vector_as_arraysegment(22); }
#endif
  public byte[] GetV2XstackArray() { return __p.__vector_as_array<byte>(22); }

  public static Offset<PosAPI> CreatePosAPI(FlatBufferBuilder builder,
      Offset<GSCMstruct> GSCMOffset = default(Offset<GSCMstruct>),
      VectorOffset GSCMvectorOffset = default(VectorOffset),
      VectorOffset CITSOffset = default(VectorOffset),
      VectorOffset posOffset = default(VectorOffset),
      VectorOffset SupplOffset = default(VectorOffset),
      bool terminateNS3 = false,
      VectorOffset GSCMSpectruChannelsOffset = default(VectorOffset),
      VectorOffset SpectrumInfoOffset = default(VectorOffset),
      int NumberOfFrequnciesPerChannel = 0,
      StringOffset V2XstackOffset = default(StringOffset)) {
    builder.StartObject(10);
    PosAPI.AddV2Xstack(builder, V2XstackOffset);
    PosAPI.AddNumberOfFrequnciesPerChannel(builder, NumberOfFrequnciesPerChannel);
    PosAPI.AddSpectrumInfo(builder, SpectrumInfoOffset);
    PosAPI.AddGSCMSpectruChannels(builder, GSCMSpectruChannelsOffset);
    PosAPI.AddSuppl(builder, SupplOffset);
    PosAPI.AddPos(builder, posOffset);
    PosAPI.AddCITS(builder, CITSOffset);
    PosAPI.AddGSCMvector(builder, GSCMvectorOffset);
    PosAPI.AddGSCM(builder, GSCMOffset);
    PosAPI.AddTerminateNS3(builder, terminateNS3);
    return PosAPI.EndPosAPI(builder);
  }

  public static void StartPosAPI(FlatBufferBuilder builder) { builder.StartObject(10); }
  public static void AddGSCM(FlatBufferBuilder builder, Offset<GSCMstruct> GSCMOffset) { builder.AddOffset(0, GSCMOffset.Value, 0); }
  public static void AddGSCMvector(FlatBufferBuilder builder, VectorOffset GSCMvectorOffset) { builder.AddOffset(1, GSCMvectorOffset.Value, 0); }
  public static void StartGSCMvectorVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(16, numElems, 8); }
  public static void AddCITS(FlatBufferBuilder builder, VectorOffset CITSOffset) { builder.AddOffset(2, CITSOffset.Value, 0); }
  public static void StartCITSVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(8, numElems, 4); }
  public static void AddPos(FlatBufferBuilder builder, VectorOffset posOffset) { builder.AddOffset(3, posOffset.Value, 0); }
  public static void StartPosVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(16, numElems, 4); }
  public static void AddSuppl(FlatBufferBuilder builder, VectorOffset SupplOffset) { builder.AddOffset(4, SupplOffset.Value, 0); }
  public static void StartSupplVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(8, numElems, 4); }
  public static void AddTerminateNS3(FlatBufferBuilder builder, bool terminateNS3) { builder.AddBool(5, terminateNS3, false); }
  public static void AddGSCMSpectruChannels(FlatBufferBuilder builder, VectorOffset GSCMSpectruChannelsOffset) { builder.AddOffset(6, GSCMSpectruChannelsOffset.Value, 0); }
  public static void StartGSCMSpectruChannelsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(24, numElems, 8); }
  public static void AddSpectrumInfo(FlatBufferBuilder builder, VectorOffset SpectrumInfoOffset) { builder.AddOffset(7, SpectrumInfoOffset.Value, 0); }
  public static void StartSpectrumInfoVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(12, numElems, 4); }
  public static void AddNumberOfFrequnciesPerChannel(FlatBufferBuilder builder, int NumberOfFrequnciesPerChannel) { builder.AddInt(8, NumberOfFrequnciesPerChannel, 0); }
  public static void AddV2Xstack(FlatBufferBuilder builder, StringOffset V2XstackOffset) { builder.AddOffset(9, V2XstackOffset.Value, 0); }
  public static Offset<PosAPI> EndPosAPI(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<PosAPI>(o);
  }
  public static void FinishPosAPIBuffer(FlatBufferBuilder builder, Offset<PosAPI> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedPosAPIBuffer(FlatBufferBuilder builder, Offset<PosAPI> offset) { builder.FinishSizePrefixed(offset.Value); }
};


}
